powerdnsadmin/routes/base.py
import base64

from flask import render_template, url_for, redirect, session, request, current_app
from flask_login import LoginManager
from flask_seasurf import SeaSurf
from flask_session_captcha import FlaskSessionCaptcha

from ..models.user import User


captcha = FlaskSessionCaptcha()
csrf = SeaSurf()
login_manager = LoginManager()


def handle_bad_request(e):
    return render_template('errors/400.html', code=400, message=e), 400


def handle_unauthorized_access(e):
    session['next'] = request.script_root + request.path
    return redirect(url_for('index.login'))


def handle_access_forbidden(e):
    return render_template('errors/403.html', code=403, message=e), 403


def handle_page_not_found(e):
    return render_template('errors/404.html', code=404, message=e), 404


def handle_internal_server_error(e):
    return render_template('errors/500.html', code=500, message=e), 500


def load_if_valid(user, method, src_ip, trust_user = False):
    try:
        auth = user.is_validate(method, src_ip, trust_user)
        if auth == False:
            return None
        else:
            # login_user(user, remember=False)
            return User.query.filter(User.id==user.id).first()
    except Exception as e:
        current_app.logger.error('Error: {0}'.format(e))
        return None


@login_manager.user_loader
def load_user(id):
    """
    This will be current_user
    """
    return User.query.get(int(id))


@login_manager.request_loader
def login_via_authorization_header_or_remote_user(request):
    # Try to login using Basic Authentication
    auth_header = request.headers.get('Authorization')
    if auth_header:

        if auth_header[:6] != "Basic ":
            return None

        auth_method = request.args.get('auth_method', 'LOCAL')
        auth_method = 'LDAP' if auth_method != 'LOCAL' else 'LOCAL'

        # Remove "Basic " from the header value
        auth_header = auth_header[6:]

        try:
            auth_header = str(base64.b64decode(auth_header), 'utf-8')
        except (UnicodeDecodeError, TypeError) as e:
            return None

        # NK: We use auth_components here as we don't know if we'll have a :, we split it maximum 1 times to grab the
        #     username, the rest of the string would be the password.
        auth_components = auth_header.split(':', maxsplit=1)

        # If we don't have two auth components (username, password), we can return
        if len(auth_components) != 2:
            return None

        (username, password) = auth_components

        user = User(username=username,
                    password=password,
                    plain_text_password=password)
        return load_if_valid(user, method=auth_method, src_ip=request.remote_addr)
    
    # Try login by checking a REMOTE_USER environment variable
    remote_user = request.remote_user
    if remote_user and current_app.config.get('REMOTE_USER_ENABLED'):
        session_remote_user = session.get('remote_user')
        
        # If we already validated a remote user against an authorization method
        # a local user should have been created in the database, so we force a 'LOCAL' auth_method
        auth_method = 'LOCAL' if session_remote_user else current_app.config.get('REMOTE_AUTH_METHOD', 'LDAP') 
        current_app.logger.debug(
            'REMOTE_USER environment variable found: attempting {0} authentication for username "{1}"'
            .format(auth_method, remote_user))
        user = User(username=remote_user.strip())
        valid_remote_user = load_if_valid(user, method=auth_method, src_ip=request.remote_addr, trust_user=True)
        
        if valid_remote_user:
            # If we were successful in authenticating a trusted remote user, store it in session
            session['remote_user'] = valid_remote_user.username

        return valid_remote_user

    return None

powerdnsadmin/routes/dashboard.py
import datetime
from collections import namedtuple
from flask import Blueprint, render_template, url_for, current_app, request, jsonify, redirect, g, session, abort
from flask_login import login_required, current_user, login_manager
from sqlalchemy import not_

from ..decorators import operator_role_required
from ..models.user import User, Anonymous
from ..models.account import Account
from ..models.account_user import AccountUser
from ..models.domain import Domain
from ..models.domain_user import DomainUser
from ..models.setting import Setting
from ..models.history import History
from ..models.server import Server
from ..models.base import db

dashboard_bp = Blueprint('dashboard',
                         __name__,
                         template_folder='templates',
                         url_prefix='/dashboard')


class ZoneTabs:
    """Config data for the zone tabs on the dashboard."""

    TabInfo = namedtuple('TabInfo', ['display_name', 'filter_pattern'])
    """Info about a single tab.

    `display_name` is the name on the tab.
    `filter_pattern` is a SQL LIKE pattern , which is case-insensitively matched against the zone
    name (without the final root-dot).

    If a filter is present, the tab will show zones that match the filter.
    If no filter is present, the tab will show zones that are not matched by any other tab filter.
    """

    tabs = {
        'forward': TabInfo("", None),
        'reverse_ipv4': TabInfo("in-addr.arpa", '%.in-addr.arpa'),
        'reverse_ipv6': TabInfo("ip6.arpa", '%.ip6.arpa'),
    }
    """Dict of unique tab id to a TabInfo."""

    order = ['forward', 'reverse_ipv4', 'reverse_ipv6']
    """List of tab ids in the order they will appear."""


@dashboard_bp.before_request
def before_request():
    # Check if user is anonymous
    g.user = current_user
    login_manager.anonymous_user = Anonymous

    # Check site is in maintenance mode
    maintenance = Setting().get('maintenance')
    if maintenance and current_user.is_authenticated and current_user.role.name not in [
        'Administrator', 'Operator'
    ]:
        return render_template('maintenance.html')

    # Manage session timeout
    session.permanent = True
    current_app.permanent_session_lifetime = datetime.timedelta(
        minutes=int(Setting().get('session_timeout')))
    session.modified = True


@dashboard_bp.route('/domains-custom/<path:tab_id>', methods=['GET'])
@login_required
def domains_custom(tab_id):
    if tab_id not in ZoneTabs.tabs:
        abort(404)

    if current_user.role.name in ['Administrator', 'Operator']:
        domains = Domain.query
    else:
        # Get query for domain to which the user has access permission.
        # This includes direct domain permission AND permission through
        # account membership
        domains = db.session.query(Domain) \
            .outerjoin(DomainUser, Domain.id == DomainUser.domain_id) \
            .outerjoin(Account, Domain.account_id == Account.id) \
            .outerjoin(AccountUser, Account.id == AccountUser.account_id) \
            .filter(
            db.or_(
                DomainUser.user_id == current_user.id,
                AccountUser.user_id == current_user.id
            ))

    template = current_app.jinja_env.get_template("dashboard_domain.html")
    render = template.make_module(
        vars={"current_user": current_user, "allow_user_view_history": Setting().get('allow_user_view_history')})

    columns = [
        Domain.name, Domain.dnssec, Domain.type, Domain.serial, Domain.master,
        Domain.account_id
    ]

    order_by = []
    for i in range(len(columns)):
        column_index = request.args.get("order[{0}][column]".format(i))
        sort_direction = request.args.get("order[{0}][dir]".format(i))
        if column_index is None:
            break
        if sort_direction != "asc" and sort_direction != "desc":
            sort_direction = "asc"

        column = columns[int(column_index)]
        order_by.append(getattr(column, sort_direction)())

    if order_by:
        domains = domains.order_by(*order_by)

    if ZoneTabs.tabs[tab_id].filter_pattern:
        # If the tab has a filter, use only that
        domains = domains.filter(Domain.name.ilike(ZoneTabs.tabs[tab_id].filter_pattern))
    else:
        # If the tab has no filter, use all the other filters in negated form
        for tab_info in ZoneTabs.tabs.values():
            if not tab_info.filter_pattern:
                continue
            domains = domains.filter(not_(Domain.name.ilike(tab_info.filter_pattern)))

    total_count = domains.count()

    search = request.args.get("search[value]")
    if search:
        start = "" if search.startswith("^") else "%"
        end = "" if search.endswith("$") else "%"

        if current_user.role.name in ['Administrator', 'Operator']:
            domains = domains.outerjoin(Account).filter(
                Domain.name.ilike(start + search.strip("^$") + end)
                | Account.name.ilike(start + search.strip("^$") + end)
                | Account.description.ilike(start + search.strip("^$") + end))
        else:
            domains = domains.filter(
                Domain.name.ilike(start + search.strip("^$") + end))

    filtered_count = domains.count()

    start = int(request.args.get("start", 0))
    length = min(int(request.args.get("length", 0)), max(100, int(Setting().get('default_domain_table_size'))))

    if length != -1:
        domains = domains[start:start + length]

    data = []
    for domain in domains:
        data.append([
            render.name(domain),
            render.dnssec(domain),
            render.type(domain),
            render.serial(domain),
            render.master(domain),
            render.account(domain),
            render.actions(domain),
        ])

    response_data = {
        "draw": int(request.args.get("draw", 0)),
        "recordsTotal": total_count,
        "recordsFiltered": filtered_count,
        "data": data,
    }
    return jsonify(response_data)


@dashboard_bp.route('/', methods=['GET', 'POST'])
@login_required
def dashboard():
    if not Setting().get('pdns_api_url') or not Setting().get(
            'pdns_api_key') or not Setting().get('pdns_version'):
        return redirect(url_for('admin.setting_pdns'))

    BG_DOMAIN_UPDATE = Setting().get('bg_domain_updates')
    if not BG_DOMAIN_UPDATE:
        current_app.logger.info('Updating zones in foreground...')
        Domain().update()
    else:
        current_app.logger.info('Updating zones in background...')

    show_bg_domain_button = BG_DOMAIN_UPDATE
    if BG_DOMAIN_UPDATE and current_user.role.name not in ['Administrator', 'Operator']:
        show_bg_domain_button = False

    # Add custom boxes to render_template
    return render_template('dashboard.html',
                           zone_tabs=ZoneTabs,
                           show_bg_domain_button=show_bg_domain_button,
                           pdns_version=Setting().get('pdns_version'))


@dashboard_bp.route('/domains-updater', methods=['GET', 'POST'])
@login_required
@operator_role_required
def domains_updater():
    current_app.logger.debug('Update zones in background')
    d = Domain().update()

    response_data = {
        "result": d,
    }
    return jsonify(response_data)

powerdnsadmin/routes/user.py
import datetime
import hashlib
import imghdr
import mimetypes

from flask import Blueprint, request, render_template, make_response, jsonify, redirect, url_for, g, session, \
    current_app, after_this_request, abort
from flask_login import current_user, login_required, login_manager

from ..models.user import User, Anonymous
from ..models.setting import Setting
from .index import password_policy_check


user_bp = Blueprint('user',
                    __name__,
                    template_folder='templates',
                    url_prefix='/user')


@user_bp.before_request
def before_request():
    # Check if user is anonymous
    g.user = current_user
    login_manager.anonymous_user = Anonymous

    # Check site is in maintenance mode
    maintenance = Setting().get('maintenance')
    if maintenance and current_user.is_authenticated and current_user.role.name not in [
            'Administrator', 'Operator'
    ]:
        return render_template('maintenance.html')

    # Manage session timeout
    session.permanent = True
    current_app.permanent_session_lifetime = datetime.timedelta(
        minutes=int(Setting().get('session_timeout')))
    session.modified = True

    # Clean up expired sessions in the database
    if Setting().get('session_type') == 'sqlalchemy':
        from ..models.sessions import Sessions
        Sessions().clean_up_expired_sessions()


@user_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'GET':
        return render_template('user_profile.html')
    if request.method == 'POST':
        if session['authentication_type'] == 'LOCAL':
            firstname = request.form.get('firstname', '').strip()
            lastname = request.form.get('lastname', '').strip()
            email = request.form.get('email', '').strip()
            new_password = request.form.get('password', '')
        else:
            firstname = lastname = email = new_password = ''
            current_app.logger.warning(
                'Authenticated externally. User {0} information will not allowed to update the profile'
                .format(current_user.username))

        if request.data:
            jdata = request.json
            data = jdata['data']
            if jdata['action'] == 'enable_otp':
                if session['authentication_type'] in ['LOCAL', 'LDAP']:
                    enable_otp = data['enable_otp']
                    user = User(username=current_user.username)
                    user.update_profile(enable_otp=enable_otp)
                    return make_response(
                        jsonify({
                            'status':
                            'ok',
                            'msg':
                            'Change OTP Authentication successfully. Status: {0}'
                            .format(enable_otp)
                        }), 200)
                else:
                    return make_response(
                        jsonify({
                            'status':
                            'error',
                            'msg':
                            'User {0} is externally. You are not allowed to update the OTP'
                            .format(current_user.username)
                        }), 400)

        (password_policy_pass, password_policy) = password_policy_check(current_user.get_user_info_by_username(), new_password)
        if not password_policy_pass:
            if request.data:
                return make_response(
                    jsonify({
                        'status': 'error',
                        'msg': password_policy['password'],
                    }), 400)
            return render_template('user_profile.html', error_messages=password_policy)

        user = User(username=current_user.username,
                    plain_text_password=new_password,
                    firstname=firstname,
                    lastname=lastname,
                    email=email,
                    reload_info=False)

        user.update_profile()

        return render_template('user_profile.html')


@user_bp.route('/qrcode')
@login_required
def qrcode():
    if not current_user:
        return redirect(url_for('index'))

    return current_user.get_qrcode_value(), 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
    }


@user_bp.route('/image', methods=['GET'])
@login_required
def image():
    """Returns the user profile image or avatar."""

    @after_this_request
    def add_cache_headers(response_):
        """When the response is ok, add cache headers."""
        if 200 <= response_.status_code <= 399:
            response_.cache_control.private = True
            response_.cache_control.max_age = int(datetime.timedelta(days=1).total_seconds())
        return response_

    def return_image(content, content_type=None):
        """Return the given binary image content. Guess the type if not given."""
        if not content_type:
            guess = mimetypes.guess_type('example.' + imghdr.what(None, h=content))
            if guess and guess[0]:
                content_type = guess[0]

        return content, 200, {'Content-Type': content_type}

    # To prevent "cache poisoning", the username query parameter is required
    if request.args.get('username', None) != current_user.username:
        abort(400)

    setting = Setting()

    if session['authentication_type'] == 'LDAP':
        search_filter = '(&({0}={1}){2})'.format(setting.get('ldap_filter_username'),
                                                 current_user.username,
                                                 setting.get('ldap_filter_basic'))
        result = User().ldap_search(search_filter, setting.get('ldap_base_dn'))
        if result and result[0] and result[0][0] and result[0][0][1]:
            user_obj = result[0][0][1]
            for key in ['jpegPhoto', 'thumbnailPhoto']:
                if key in user_obj and user_obj[key] and user_obj[key][0]:
                    current_app.logger.debug(f'Return {key} from ldap as user image')
                    return return_image(user_obj[key][0])

    email = current_user.email
    if email and setting.get('gravatar_enabled'):
        hash_ = hashlib.md5(email.encode('utf-8')).hexdigest()
        url = f'https://s.gravatar.com/avatar/{hash_}?s=100'
        current_app.logger.debug('Redirect user image request to gravatar')
        return redirect(url, 307)

    # Fallback to the local default image
    return current_app.send_static_file('img/user_image.png')

powerdnsadmin/templates/admin_edit_user.html
{% extends "base.html" %}
{% set active_page = "admin_users" %}
{% if create %}
    {% set action_label = 'Create' %}
    {% set form_action = url_for('admin.edit_user') %}
{% else %}
    {% set action_label = 'Edit' %}
    {% set form_action = url_for('admin.edit_user', user_username=user.username) %}
{% endif %}
{% block title %}<title>{{ action_label }} User - {{ SITE_NAME }}</title>{% endblock %}

{% block dashboard_stat %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{ action_label }} User</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ url_for('admin.manage_user') }}">Users</a></li>
                        <li class="breadcrumb-item active">{{ action_label }} User</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-6 col-lg-4">
                    <form role="form" method="post" action="{{ form_action }}">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="create" value="{{ create }}">
                        <div class="card card-outline card-primary shadow">
                            <div class="card-header with-border">
                                <h3 class="card-title">User Editor</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                {% if error %}
                                    <div class="alert alert-danger alert-dismissible">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                            &times;
                                        </button>
                                        <h4><i class="fa-solid fa-ban"></i> Error!</h4>
                                        {{ error }}
                                    </div>
                                    <span class="help-block">{{ error }}</span>
                                {% endif %}
                                <div class="form-group has-feedback">
                                    <label class="control-label" for="firstname">First Name</label>
                                    <input type="text" class="form-control" placeholder="First Name" name="firstname"
                                           id="firstname"
                                           {% if user %}value="{{ user.firstname }}" {% endif %}>
                                    <span class="form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <label class="control-label" for="lastname">Last Name</label>
                                    <input type="text" class="form-control" placeholder="Last name" name="lastname"
                                           id="lastname"
                                           {% if user %}value="{{ user.lastname }}" {% endif %}>
                                    <span class="form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <label class="control-label" for="email">E-mail address</label>
                                    <input type="email" class="form-control" placeholder="Email" name="email" id="email"
                                           {% if user %}value="{{ user.email }}" {% endif %}>
                                    <span class="form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <label class="control-label" for="username">Username</label>
                                    <input type="text" class="form-control" placeholder="Username" name="username"
                                           id="username"
                                           {% if user %}value="{{ user.username }}" {% endif %}
                                           {% if not create %}disabled{% endif %}>
                                    <span class="form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback {% if blank_password %}has-error{% endif %}">
                                    <label class="control-label" for="password">Password</label>
                                    <input type="password" class="form-control"
                                           placeholder="Password {% if create %}(Required){% else %}(Leave blank to keep unchanged){% endif %}"
                                           name="password" id="password">
                                    <span class="form-control-feedback"></span>
                                    {% if blank_password %}
                                        <span class="help-block">The password cannot be blank.</span>
                                    {% endif %}
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary" title="{{ action_label }} User">
                                    {{ action_label }} User
                                </button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    </form>
                    {% if not create %}
                        {% if user.otp_secret %}
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Two Factor Authentication</h3>
                                </div>
                                <div class="card-body">
                                    <p>If two-factor authentication is configured for this user and is causing problems
                                        due to a lost device or
                                        technical issue, it can be disabled here.
                                    </p>
                                    <p>The user will need to reconfigure two-factor authentication, to re-enable it.</p>
                                    <p><strong>Beware: This could compromise security!</strong></p>
                                </div>
                                <div class="card-footer">
                                    <button type="button" class="btn btn-warning button_otp_disable"
                                            id="{{ user.username }}">
                                        Disable Two Factor Authentication
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
                <!-- /.col -->

                <div class="col-12 col-sm-6 col-lg-8">
                    <div class="card card-outline card-secondary shadow">
                        <div class="card-header">
                            <h3 class="card-title">User Editor Help</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <p>Fill in all the fields to the in the form to the left.</p>
                            {% if create %}
                                <p><strong>Newly created users do not have access to any zones.</strong> You will need
                                    to grant
                                    access to the user once it is created via the zone management buttons on the
                                    dashboard.
                                </p>
                            {% else %}
                                <p><strong>Username</strong> cannot be changed.</p>
                                <p><strong>Password</strong> can be left empty to keep the current password.</p>
                            {% endif %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
{% endblock %}

{% block extrascripts %}
    <script>
        // handle disabling two-factor authentication
        $(document.body).on('click', '.button_otp_disable', function () {
            var modal = $("#modal_otp_disable");
            var username = $(this).prop('id');
            var info = "Are you sure you want to disable two factor authentication for user " + username + "?";
            modal.find('.modal-body p').text(info);
            modal.find('#button_otp_disable_confirm').click(function () {
                var postdata = {
                    'action': 'user_otp_disable',
                    'data': username,
                    '_csrf_token': '{{ csrf_token() }}'
                }
                applyChanges(postdata, $SCRIPT_ROOT + '/admin/manage-user', false, true);
            })
            modal.modal('show');
        });
    </script>
{% endblock %}

{% block modals %}
    <div class="modal fade modal-warning" id="modal_otp_disable">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Confirmation</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                    <button type="button" class="btn btn-danger float-right" id="button_otp_disable_confirm">
                        Disable Two Factor Authentication
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

powerdnsadmin/templates/dyndns.html
{{ response }}

powerdnsadmin/templates/maintenance.html
<!DOCTYPE html>
<html lang="en" class>
<head>
    <title>Site Maintenance</title>
    <style>
        body {
            text-align: center;
            padding: 150px;
        }

        h1 {
            font-size: 50px;
        }

        body {
            font: 20px Helvetica, sans-serif;
            color: #333;
        }

        article {
            display: block;
            text-align: left;
            width: 650px;
            margin: 0 auto;
        }

        a {
            color: #dc8100;
            text-decoration: none;
        }

        a:hover {
            color: #333;
            text-decoration: none;
        }
    </style>
</head>
<body>
<article>
    <h1>We&rsquo;ll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. Please contact the
            System
            Administrator if you need more information, otherwise we&rsquo;ll be back online shortly!</p>
        <p>&mdash; Team</p>
    </div>
</article>
</body>
</html>